# Déploiement Nginx pour Dounie Cuisine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dounie-nginx
  namespace: dounie-cuisine
  labels:
    app: dounie-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dounie-nginx
  template:
    metadata:
      labels:
        app: dounie-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-default-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: nginx-config
        configMap:
          name: dounie-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nginx-default-config
        configMap:
          name: dounie-config
          items:
          - key: default.conf
            path: default.conf
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dounie-nginx-service
  namespace: dounie-cuisine
spec:
  selector:
    app: dounie-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: LoadBalancer