# Déploiement PostgreSQL pour Dounie Cuisine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dounie-postgres
  namespace: dounie-cuisine
  labels:
    app: dounie-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dounie-postgres
  template:
    metadata:
      labels:
        app: dounie-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "dounie_cuisine"
        - name: POSTGRES_USER
          value: "dounie_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dounie-secrets
              key: DB_PASSWORD
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF-8 --lc-collate=fr_FR.UTF-8 --lc-ctype=fr_FR.UTF-8"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-backups
          mountPath: /backups
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - dounie_user
            - -d
            - dounie_cuisine
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - dounie_user
            - -d
            - dounie_cuisine
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-backups
        persistentVolumeClaim:
          claimName: backups-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dounie-postgres
  namespace: dounie-cuisine
spec:
  selector:
    app: dounie-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP